data_info:
  data_dir: ./data  # contralearn/
  wav_dir: ./data/wav  # ../contralearn/data/wav
  model_dir: ./pth
  kmeans_dir: ./pth/kmeans
  feat_dir: ./feat
  fs: 16000
  n_mels: 128
  n_fft: 1024
  hop_hength: 512
  tar_time: 10
  patch_len: 100  # 101
  distance: 25
  CL_pos_mix_alpha: 0.05  # 0.02; 0.05 win; 0.1 0.2

mach_index:
  0: 'fan'
  1: 'gearbox'
  2: 'bearing'
  3: 'slider'
  4: 'valve'
  5: 'ToyCar'
  6: 'ToyTrain'

man_control:
  choose_model_nums: 1
  kmean_draw3D: 'False'  # True False
  mix_up: 'False'  # True False
  ext_way: 'logmels'  # logmel
  zero_normal: True  # True False
  feat_normal: True  # True False
  premodel_ext: 'True' # True False
  kmean_needtrain: False # True False 
  kmeans_needtest: True
  clip_way: 'Distance'  # 'Random', 'Distance'
  learn_method: 'Contrastive'  # 'Contrastive' , 'False'
  data_ext_way: 'contraN'  # 'raw', 'rawclip', 'contra','contraN','contraaugN'
  mix_way: 'linear' # 'linear', 'energy'
  loss_mode: 'clscontra_'  #, cls_,'contra_', 'clscontra_'
  loss_choice: 'ArcFace'  # 'ArcFace', 'SupCon'
  model_name: 'MobileNetV2'  # 'MobileNetV2', 'ResNetL', 'ResNet18'
  

cuda: 1
mode: 'train'  # train, test
train_pickle: 'train_logmels.joblib'
test_pickle: 'test_logmels.joblib'  # test_Tarlogmel test_logmel
data_name: 'logmels'
cur_domain: 'target'  # source target
machID: '00'  # dcase24 = '' , dcase22='00' '01' '02'

train:
  global_pooling: "gap"  # "gap" "gapgmp"
  head_num: 1
  head_size: 2
  emb_dim:
    'MobileNetV2': 1280  # feat size: B*1*8*7 for B*1*128*150
    'ResNetL': 512
    'ResNet18': 512  # feat size: B*1*4*5 for B*1*128*150
    'VGG': 512
    'CRNN': 64
    'Pyramid': 8064

  mlp_hidden_size: 512
  low_dim: 512
  temp: 0.2  # 0.2* 0.3  [0.05,0.5]
  contra_loss_weight: 0.3  # 0.3*
  input_dim: 1  # 101 1 2
  seed: 25634
  new_seed: 123
  batch_size: 128  # 32
  epoch: 200  # 100 500*
  lr: 0.03  # 0.0001 0.03*
  weight_decay: 1e-4  #3e-5  1e-4*
  threshold_count: 98
  decimal_count: 6
  loss_thre: 0.005
  threshold_alpha: 1
  pauc_value: 0.1
  n_neighbors: 5  # 3 6
  class_num: 7
  detect_num: 2
  num_workers: 0
  alpha: 1.28

kmeans_model:
  max_iter: 300
  tol: 1e-4

da:
  # RandTimeShift
  do_rand_time_shift: false
  Tshift: 30
  # RandFreqShift
  do_rand_freq_shift: false
  Fshift: 10
  # RandomResizedCrop_diy
  do_randcrop: false
  rc_scale: #!!python/tuple
  - 0.8
  - 1
  rc_ratio: #!!python/tuple
  - 0.75
  - 1.3333333333333333
  # TimeReversal
  do_time_reversal: false
  # Compander
  do_compansion: false
  comp_alpha: 0.75
  #SpecAugment
  do_time_warp: false
  SpecAugment_W: -1
  do_freq_mask: false
  SpecAugment_F: 20
  SpecAugment_m_f: 2
  reduce_mask_range: 0
  do_time_mask: false
  SpecAugment_T: 20
  SpecAugment_m_t: 2
  SpecAugment_mask_val: min
  # GaussNoise
  awgn_stdev_gen: 0.0
  # RandomGaussianBlur
  do_blur: false
  blur_max_ksize: -1
  blur_stdev_x: -1
